name: radiance
description: A collection of AI algorithms for game development
version: 0.0.0
homepage: https://github.com/flame-engine/radiance

environment:
  sdk: '>=2.14.0 <3.0.0'

dev_dependencies:
  flutter:
    sdk: flutter
  test: ^1.17.0
  flame_test: ^1.0.1
  flame_lint: ^0.0.1
